### ISSUE TITLE
Consider making Pattern API public

### ISSUE THREAD

**Issue by tomstoneham** [lewisclark/patternscan#3]
One thought I've had while working with this crate is that it would be nice if the `Pattern` and `PatternByte` APIs were publicly exposed. My reasoning for this is that it would allow developers who know the search pattern at compile time to just pass a `Pattern` to `scan` directly, without the need for parsing a pattern string. Furthermore, this goes some way to enforce compile-time checking of known patterns, as if a `Pattern` is constructed from `u8`s directly, it must inherently be valid.

I'm happy to put together a pull request for this if you agree it would be useful, just interested to hear your thoughts before I go ahead.

**Comment by lewisclark** [comment]
I think this would be a nice change. I think it's safe to say that the majority of people using this crate will know their patterns at compile-time, so this makes a lot of sense.
